spring:
  application:
    name: audio-knowledge-base
  datasource:
    url: jdbc:postgresql://localhost:5432/vector_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  ai:
    mcp:
      server:
        enabled: true
        name: "coach-search-mcp"
        protocol: SSE


dashscope:
  api-key: ${DASHSCOPE_API_KEY:sk-a01bc6f7257d43cfabd61b875fc1b5a6}
  base-url: https://dashscope.aliyuncs.com/api/
  asr:
    model: paraformer-realtime-v2
    format: mp3
    sample-rate: 16000
  embedding:
    base-url: https://dashscope.aliyuncs.com/compatible-mode/v1/
    model: text-embedding-v4
    dimensions: 1024

recording:
  base-dir: C:\Users\cn-silversu\Desktop\recording

server:
  port: 8080

